// Liste des 66 livres de la Bible (Louis Segond) avec nombre de chapitres
// Format compatible avec l'API bolls.life (translation: LSG)
const BIBLE_BOOKS = [
  { id: 1, name: "Genèse", short: "Gen", chapters: 50, testament: "AT" },
  { id: 2, name: "Exode", short: "Exo", chapters: 40, testament: "AT" },
  { id: 3, name: "Lévitique", short: "Lev", chapters: 27, testament: "AT" },
  { id: 4, name: "Nombres", short: "Nom", chapters: 36, testament: "AT" },
  { id: 5, name: "Deutéronome", short: "Deu", chapters: 34, testament: "AT" },
  { id: 6, name: "Josué", short: "Jos", chapters: 24, testament: "AT" },
  { id: 7, name: "Juges", short: "Jug", chapters: 21, testament: "AT" },
  { id: 8, name: "Ruth", short: "Rut", chapters: 4, testament: "AT" },
  { id: 9, name: "1 Samuel", short: "1Sa", chapters: 31, testament: "AT" },
  { id: 10, name: "2 Samuel", short: "2Sa", chapters: 24, testament: "AT" },
  { id: 11, name: "1 Rois", short: "1Ro", chapters: 22, testament: "AT" },
  { id: 12, name: "2 Rois", short: "2Ro", chapters: 25, testament: "AT" },
  { id: 13, name: "1 Chroniques", short: "1Ch", chapters: 29, testament: "AT" },
  { id: 14, name: "2 Chroniques", short: "2Ch", chapters: 36, testament: "AT" },
  { id: 15, name: "Esdras", short: "Esd", chapters: 10, testament: "AT" },
  { id: 16, name: "Néhémie", short: "Neh", chapters: 13, testament: "AT" },
  { id: 17, name: "Esther", short: "Est", chapters: 10, testament: "AT" },
  { id: 18, name: "Job", short: "Job", chapters: 42, testament: "AT" },
  { id: 19, name: "Psaumes", short: "Psa", chapters: 150, testament: "AT" },
  { id: 20, name: "Proverbes", short: "Pro", chapters: 31, testament: "AT" },
  { id: 21, name: "Ecclésiaste", short: "Ecc", chapters: 12, testament: "AT" },
  { id: 22, name: "Cantique des Cantiques", short: "Can", chapters: 8, testament: "AT" },
  { id: 23, name: "Ésaïe", short: "Esa", chapters: 66, testament: "AT" },
  { id: 24, name: "Jérémie", short: "Jer", chapters: 52, testament: "AT" },
  { id: 25, name: "Lamentations", short: "Lam", chapters: 5, testament: "AT" },
  { id: 26, name: "Ézéchiel", short: "Eze", chapters: 48, testament: "AT" },
  { id: 27, name: "Daniel", short: "Dan", chapters: 12, testament: "AT" },
  { id: 28, name: "Osée", short: "Ose", chapters: 14, testament: "AT" },
  { id: 29, name: "Joël", short: "Joe", chapters: 3, testament: "AT" },
  { id: 30, name: "Amos", short: "Amo", chapters: 9, testament: "AT" },
  { id: 31, name: "Abdias", short: "Abd", chapters: 1, testament: "AT" },
  { id: 32, name: "Jonas", short: "Jon", chapters: 4, testament: "AT" },
  { id: 33, name: "Michée", short: "Mic", chapters: 7, testament: "AT" },
  { id: 34, name: "Nahum", short: "Nah", chapters: 3, testament: "AT" },
  { id: 35, name: "Habacuc", short: "Hab", chapters: 3, testament: "AT" },
  { id: 36, name: "Sophonie", short: "Sop", chapters: 3, testament: "AT" },
  { id: 37, name: "Aggée", short: "Agg", chapters: 2, testament: "AT" },
  { id: 38, name: "Zacharie", short: "Zac", chapters: 14, testament: "AT" },
  { id: 39, name: "Malachie", short: "Mal", chapters: 4, testament: "AT" },
  { id: 40, name: "Matthieu", short: "Mat", chapters: 28, testament: "NT" },
  { id: 41, name: "Marc", short: "Mar", chapters: 16, testament: "NT" },
  { id: 42, name: "Luc", short: "Luc", chapters: 24, testament: "NT" },
  { id: 43, name: "Jean", short: "Jea", chapters: 21, testament: "NT" },
  { id: 44, name: "Actes", short: "Act", chapters: 28, testament: "NT" },
  { id: 45, name: "Romains", short: "Rom", chapters: 16, testament: "NT" },
  { id: 46, name: "1 Corinthiens", short: "1Co", chapters: 16, testament: "NT" },
  { id: 47, name: "2 Corinthiens", short: "2Co", chapters: 13, testament: "NT" },
  { id: 48, name: "Galates", short: "Gal", chapters: 6, testament: "NT" },
  { id: 49, name: "Éphésiens", short: "Eph", chapters: 6, testament: "NT" },
  { id: 50, name: "Philippiens", short: "Phi", chapters: 4, testament: "NT" },
  { id: 51, name: "Colossiens", short: "Col", chapters: 4, testament: "NT" },
  { id: 52, name: "1 Thessaloniciens", short: "1Th", chapters: 5, testament: "NT" },
  { id: 53, name: "2 Thessaloniciens", short: "2Th", chapters: 3, testament: "NT" },
  { id: 54, name: "1 Timothée", short: "1Ti", chapters: 6, testament: "NT" },
  { id: 55, name: "2 Timothée", short: "2Ti", chapters: 4, testament: "NT" },
  { id: 56, name: "Tite", short: "Tit", chapters: 3, testament: "NT" },
  { id: 57, name: "Philémon", short: "Phm", chapters: 1, testament: "NT" },
  { id: 58, name: "Hébreux", short: "Heb", chapters: 13, testament: "NT" },
  { id: 59, name: "Jacques", short: "Jac", chapters: 5, testament: "NT" },
  { id: 60, name: "1 Pierre", short: "1Pi", chapters: 5, testament: "NT" },
  { id: 61, name: "2 Pierre", short: "2Pi", chapters: 3, testament: "NT" },
  { id: 62, name: "1 Jean", short: "1Je", chapters: 5, testament: "NT" },
  { id: 63, name: "2 Jean", short: "2Je", chapters: 1, testament: "NT" },
  { id: 64, name: "3 Jean", short: "3Je", chapters: 1, testament: "NT" },
  { id: 65, name: "Jude", short: "Jud", chapters: 1, testament: "NT" },
  { id: 66, name: "Apocalypse", short: "Apo", chapters: 22, testament: "NT" },
];

const TRANSLATIONS = [
  { code: "FRLSG", name: "Louis Segond 1910" },
  { code: "FRPDV17", name: "Parole de Vie 2017" },
  { code: "BDS", name: "Bible du Semeur 2015" },
  { code: "NBS", name: "Nouvelle Bible Segond 2002" },
  { code: "FRDBY", name: "Bible de Darby 1890" },
];
